### ISSUE TITLE
Install error on civicrm 4.5

### ISSUE THREAD

**Issue by magnolia61** [CiviCooP/org.civicoop.emailapi#1]
Hi Jaap, we get an error when installing the latest release (and master code). Would you think this points to a 4.6 specific issue? Installing on 4.5 gives us no problem. I know the emailapi is officially not 4.6 supported, but maybe my issue helps getting there :-)

Warning: Invalid argument supplied for foreach() in _emailapi_civix_civicrm_managed() (regel 171 van /home/xyz/domains/ourdomain.nl/public_html/live/sites/all/modules/civicrm_extensions/org.civicoop.emailapi/emailapi.civix.php).

**Comment by jaapjansma** [comment]
Duplicate of #2
