### ISSUE TITLE
Install error on civicrm 4.6

### ISSUE THREAD

**Issue by magnolia61** [CiviCooP/org.civicoop.emailapi#2]
Hi Jaap, we get an error when installing the latest release (and master code). Would you think this points to a 4.6 specific issue? Installing on 4.5 gives us no problem. I know the emailapi is officially not 4.6 supported, but maybe my issue helps getting there :-)

Warning: Invalid argument supplied for foreach() in _emailapi_civix_civicrm_managed() (regel 171 van /home/xyz/domains/ourdomain.nl/public_html/live/sites/all/modules/civicrm_extensions/org.civicoop.emailapi/emailapi.civix.php).

**Comment by jaapjansma** [comment]
Hey Richard,

I am managing a CiviCRM 4.6 site where this issues did not arise. Also I now from another organization using CiviCRM 4.6 and the e-mail api and haven't heard they had problems. 

So it might be that it is something specific to your install but not sure what....

Jaap

**Comment by ErikHommel** [comment]
Closing this issue as no other mentions were made.
