### ISSUE TITLE
emailapi 1.17.2 fails upgrade when CiviRules isn't installed

### ISSUE THREAD

**Issue by MegaphoneJon** [CiviCooP/org.civicoop.emailapi#26]
The upgrade fails with a "DB Error: No such table", for the obvious reason.

I'm realizing I no longer need this extension on this site, but if CiviRules isn't a dependency of this extension, IMO the upgrade lines should be wrapped in a conditional.

**Comment by rrooij** [comment]
Same problem here.

**Comment by haraldballuch** [comment]
The problem persists in version 1.19
Probably the sql executions in function upgrade_1003 (in CRM/Emailapi/Upgrader) should be wrapped in a conditional like if(civicrm_api3('Extension', 'get', ['key' => 'civirules', 'status' => 'installed'])['count'])?

**Comment by jaapjansma** [comment]
Makes sense @haraldballuch a PR is very welcome.

**Comment by jaapjansma** [comment]
@haraldballuch thanks for your PR
