### ISSUE TITLE
Smarty error with CSS in message templates

### ISSUE THREAD

**Issue by klevie** [CiviCooP/org.civicoop.emailapi#4]
When using an message template that contains any CSS (`<style> body { } </style>`), calling the Email.send method returns a fatal error (and any rule actions that depend on it are aborted).
The same message _is_ sent correctly when sending a CiviMail mailing or a manual email to one contact.   

On [line 144-146 of Email/Send.php](https://github.com/CiviCooP/org.civicoop.emailapi/blob/master/api/v3/Email/Send.php#L144) a Smarty call is done for the email body (and then on line 156 for the email message).
Even when I disable these lines, tokens like `{contact.email_greeting}` are still parsed correctly (perhaps also using a more sophisticated Smarty method than the one called here?).
Enabling advanced Smarty logic in templates shouldn't have to be hardcoded and is always possible by setting `CIVICRM_MAIL_SMARTY` to 1 in civicrm.settings.php.

Therefore, if I'm not mistaken, these lines can be safely removed from this API method.
As of now I have only tested this myself on CiviCRM 4.7.9 (on WP + CiviRules 1.2).

**Comment by ErikHommel** [comment]
Do not see any Smarty call in the mentioned statements. The Smarty calls that are in the code are based on CIVICRM_MAIL_SMARTY. Issue us almost 2 years old, closing it now.
