### ISSUE TITLE
Does CivirulesAction.mgd.php need: else {return array();}

### ISSUE THREAD

**Issue by petednz** [CiviCooP/org.civicoop.emailapi#6]
totten suggested " i think the problem is in CRM/Emailapi/CivirulesAction.mgd.php. An mgd.php file should always return an array, but this one only does so conditionally.  Try adding something like else { return array(); } at the bottom"

https://chat.civicrm.org/civicrm/pl/jhnc7ds5gjdxiq4a6tqdjfnndc

**Comment by jaapjansma** [comment]
@petednz thanks for your comment and it makes sense what totten suggested. Could you add this to the mgd file and send a PR?

**Comment by petednz** [comment]
Done
