### ISSUE TITLE
Support for 4.7?

### ISSUE THREAD

**Issue by GinkgoFJG** [CiviCooP/org.civicoop.emailapi#8]
Hello, this extension is not flagged as 4.7-compatible. I installed it in a 4.7 sandbox and did a little playing around (though not a thorough test), and I didn't find anything to be broken. Are there known issues with 4.7? Thanks!

**Comment by jaapjansma** [comment]
I don't know of any known issues for 4.7. If there would be issues they would be in the issue tracker. 

There is another side note here is that we are not so keen in providing compatibility flags or keeping them up-to-date as that would make me a supplier and I don't want to be a supplier as I am not committed in maintaining anything I have created. I am committed to work with clients and do maintenance on their behalf but that is mostly tied to their installation and the issues they face. 
So there are two sides to this issue: setting the flag to 4.7 implies that the extension works out of the box and I can never guarantee that; not setting the flag implies that the extension does not work with 4.7 but even that is I can not state. 

That said if I know there are many people using this extension in 4.7 installation without any problems I am happy to change the flag. And if you say it works after you have tested I am more than happy to trust you. 
And feel free to provide pull requests in case there are any issues.

**Comment by Upperholme** [comment]
It seems to be working fine for me with 4.7.

**Comment by jaapjansma** [comment]
I have flagged this extension as 4.7 compatible.
